workflows:
  ios:
    name: ios-build-no-signing
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          cd iosApp 
          flutter pub get
          gem install cocoapods -v 1.16.1 # Установка конкретной версии CocoaPods
          pod install
      - name: Build iOS App (No Code Signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - iosApp/*.ipa
