workflows:
  ios:
    name: ios-build-no-signing
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          chmod +x gradlew  # Убедитесь, что gradlew имеет права на выполнение
          ./gradlew clean build
      - name: Build iOS App (No Code Signing)
        script: |
          cd iosApp  # Переход в директорию с iOS проектом
          xcodebuild -project iosApp.xcodeproj -configuration Debug -destination "platform=iOS Simulator,name=iPhone 14" clean build CODE_SIGNING_REQUIRED=NO
    artifacts:
      - iosApp/build/ios/ipa/*.ipa  # Путь к артефактам .ipa, измените путь в соответствии с результатами сборки
